train: /content/drive/MyDrive/New_data/fixed_yolo_data/images/train/
val: /content/drive/MyDrive/New_data/fixed_yolo_data/images/val/
nc: 5

names: ['rubbish','mattress', 'furniture', 'chair', 'electrical goods']